spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/agua
spring.datasource.username=postgres
spring.datasource.password=Proyectos78$

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true